name: Frontend CI/CD

on:
  push:
    branches: [main]
    paths:
      - "src/main/frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "src/main/frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: "./yarn.lock"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Build packages
        run: yarn build:packages

      - name: Clean and reinstall frontend dependencies
        run: |
          cd src/main/frontend
          rm -rf node_modules
          yarn install

      - name: Sync version to .env
        run: yarn version:sync

      - name: Create .env file
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> src/main/frontend/.env
          echo "REACT_APP_KAKAO_REST_APP_KEY=${{ secrets.REACT_APP_KAKAO_REST_APP_KEY }}" >> src/main/frontend/.env
          echo "REACT_APP_GOOGLE_AUTH_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_AUTH_CLIENT_ID }}" >> src/main/frontend/.env

      - name: Build project
        env:
          CI: false
        run: yarn workspace frontend build

      - name: Debug Info Before Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          echo "âœ… í˜„ì¬ ë¸Œëœì¹˜: ${{ github.ref }}"
          echo "âœ… Build ë””ë ‰í† ë¦¬ ì‚¬ì´ì¦ˆ:"
          du -sh src/main/frontend/build/
          echo "âœ… Build ë””ë ‰í† ë¦¬ ëª©ë¡:"
          ls -la src/main/frontend/build/
          echo "ğŸ”¥ ë°°í¬ ëŒ€ìƒ ë²„í‚· ì´ë¦„: ${{ secrets.AWS_S3_BUCKET }}"

      - name: Deploy to S3
        if: github.ref == 'refs/heads/main'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --debug
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }} # mooddisk-assets
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
          SOURCE_DIR: "./src/main/frontend/build"

      - name: Debug Info After Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          echo "âœ… S3 ë²„í‚·ì— ì—…ë¡œë“œ ì™„ë£Œ! í˜„ì¬ S3 íŒŒì¼ ëª©ë¡:"
          aws s3 ls s3://${{ secrets.AWS_S3_BUCKET }} --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"

      - name: Invalidate CloudFront Cache
        if: github.ref == 'refs/heads/main'
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: |
            /*
          AWS_REGION: "ap-northeast-2"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
